# Generated by Django 3.1.2 on 2020-12-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_auto_20201212_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(choices=[('O', 'Oscar'), ('A', 'Academy Award'), ('S', 'Screen Actors Guild')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='movies_app.Performer'),
        ),
    ]
